In [1]:
import yfinance as yf
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
Apple = yf.download("AAPL", start = "2010-01-01",end = "2021-01-01")

[*********************100%***********************]  1 of 1 completed

In [5]:
Ticker = ['SPY','AAPL','KO']

In [24]:
Stocks = yf.download(Ticker, start = "2010-01-01",end = "2021-01-01")

[*********************100%***********************]  3 of 3 completed

In [25]:
Stocks

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.515212  19.081619   88.454185    7.643214  28.520000
2010-01-05    6.526476  18.850790   88.688332    7.656429  28.174999
2010-01-06    6.422665  18.844097   88.750771    7.534643  28.165001
2010-01-07    6.410791  18.797268   89.125435    7.520714  28.094999
2010-01-08    6.453413  18.449360   89.422005    7.570714  27.575001
...                ...        ...         ...         ...        ...
2020-12-24  130.404587  50.318054  358.332611  131.970001  53.439999
2020-12-28  135.068604  50.995991  361.410980  136.690002  54.160000
2020-12-29  133.270187  50.967743  360.721527  134.869995  54.130001
2020-12-30  132.133835  51.259632  361.236206  133.720001  54.439999
2020-12-31  131.116043  51.636265  363.071594  132.690002  54.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04  113.330002    7.660714  28.610001  113.389999    7.585000
2010-01-05  113.629997    7.699643  28.495001  113.680000    7.616071
2010-01-06  113.709999    7.686786  28.219999  113.989998    7.526786
2010-01-07  114.190002    7.571429  28.184999  114.330002    7.466071
2010-01-08  114.570000    7.571429  27.820000  114.620003    7.466429
...                ...         ...        ...         ...         ...
2020-12-24  369.000000  133.460007  53.549999  369.029999  131.100006
2020-12-28  372.170013  137.339996  54.439999  372.589996  133.509995
2020-12-29  371.459991  138.789993  54.490002  374.000000  134.339996
2020-12-30  371.989990  135.990005  54.630001  373.100006  133.399994
2020-12-31  373.880005  134.740005  54.930000  374.660004  131.720001

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2010-01-04  28.450001  111.510002    7.622500  28.580000  112.370003
2010-01-05  28.070000  112.849998    7.664286  28.424999  113.260002
2010-01-06  27.990000  113.430000    7.656429  28.174999  113.519997
2010-01-07  27.875000  113.180000    7.562500  28.165001  113.500000
2010-01-08  27.375000  113.660004    7.510714  27.730000  113.889999
...               ...         ...         ...        ...         ...
2020-12-24  53.020000  367.450012  131.320007  53.020000  368.079987
2020-12-28  53.730000  371.070007  133.990005  53.849998  371.739990
2020-12-29  54.020000  370.829987  138.050003  54.450001  373.809998
2020-12-30  54.029999  371.570007  135.580002  54.049999  372.339996
2020-12-31  54.270000  371.230011  134.080002  54.450001  371.779999

               Volume
                 AAPL        KO        SPY
Date
2010-01-04  493729600  13870400  118944600
2010-01-05  601904800  23172400  111579900
2010-01-06  552160000  19264600  116074400
2010-01-07  477131200  13234600  131091100
2010-01-08  447610800  28712400  126402800
...               ...       ...        ...
2020-12-24   54930100   3265500   26457900
2020-12-28  124486200   9020500   39000400
2020-12-29  121047300   8320600   53680500
2020-12-30   96452100   8142700   49455300
2020-12-31   99116600   8495000   78520700

[2769 rows x 18 columns]

In [26]:
Stocks.head()

           Adj Close                           Close                         \
                AAPL         KO        SPY      AAPL         KO         SPY
Date
2010-01-04  6.515212  19.081619  88.454185  7.643214  28.520000  113.330002
2010-01-05  6.526476  18.850790  88.688332  7.656429  28.174999  113.629997
2010-01-06  6.422665  18.844097  88.750771  7.534643  28.165001  113.709999
2010-01-07  6.410791  18.797268  89.125435  7.520714  28.094999  114.190002
2010-01-08  6.453413  18.449360  89.422005  7.570714  27.575001  114.570000

                High                              Low                         \
                AAPL         KO         SPY      AAPL         KO         SPY
Date
2010-01-04  7.660714  28.610001  113.389999  7.585000  28.450001  111.510002
2010-01-05  7.699643  28.495001  113.680000  7.616071  28.070000  112.849998
2010-01-06  7.686786  28.219999  113.989998  7.526786  27.990000  113.430000
2010-01-07  7.571429  28.184999  114.330002  7.466071  27.875000  113.180000
2010-01-08  7.571429  27.820000  114.620003  7.466429  27.375000  113.660004

                Open                            Volume
                AAPL         KO         SPY       AAPL        KO        SPY
Date
2010-01-04  7.622500  28.580000  112.370003  493729600  13870400  118944600
2010-01-05  7.664286  28.424999  113.260002  601904800  23172400  111579900
2010-01-06  7.656429  28.174999  113.519997  552160000  19264600  116074400
2010-01-07  7.562500  28.165001  113.500000  477131200  13234600  131091100
2010-01-08  7.510714  27.730000  113.889999  447610800  28712400  126402800

In [27]:
stocks = pd.DataFrame(Stocks)
stocks

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.515212  19.081619   88.454185    7.643214  28.520000
2010-01-05    6.526476  18.850790   88.688332    7.656429  28.174999
2010-01-06    6.422665  18.844097   88.750771    7.534643  28.165001
2010-01-07    6.410791  18.797268   89.125435    7.520714  28.094999
2010-01-08    6.453413  18.449360   89.422005    7.570714  27.575001
...                ...        ...         ...         ...        ...
2020-12-24  130.404587  50.318054  358.332611  131.970001  53.439999
2020-12-28  135.068604  50.995991  361.410980  136.690002  54.160000
2020-12-29  133.270187  50.967743  360.721527  134.869995  54.130001
2020-12-30  132.133835  51.259632  361.236206  133.720001  54.439999
2020-12-31  131.116043  51.636265  363.071594  132.690002  54.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04  113.330002    7.660714  28.610001  113.389999    7.585000
2010-01-05  113.629997    7.699643  28.495001  113.680000    7.616071
2010-01-06  113.709999    7.686786  28.219999  113.989998    7.526786
2010-01-07  114.190002    7.571429  28.184999  114.330002    7.466071
2010-01-08  114.570000    7.571429  27.820000  114.620003    7.466429
...                ...         ...        ...         ...         ...
2020-12-24  369.000000  133.460007  53.549999  369.029999  131.100006
2020-12-28  372.170013  137.339996  54.439999  372.589996  133.509995
2020-12-29  371.459991  138.789993  54.490002  374.000000  134.339996
2020-12-30  371.989990  135.990005  54.630001  373.100006  133.399994
2020-12-31  373.880005  134.740005  54.930000  374.660004  131.720001

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2010-01-04  28.450001  111.510002    7.622500  28.580000  112.370003
2010-01-05  28.070000  112.849998    7.664286  28.424999  113.260002
2010-01-06  27.990000  113.430000    7.656429  28.174999  113.519997
2010-01-07  27.875000  113.180000    7.562500  28.165001  113.500000
2010-01-08  27.375000  113.660004    7.510714  27.730000  113.889999
...               ...         ...         ...        ...         ...
2020-12-24  53.020000  367.450012  131.320007  53.020000  368.079987
2020-12-28  53.730000  371.070007  133.990005  53.849998  371.739990
2020-12-29  54.020000  370.829987  138.050003  54.450001  373.809998
2020-12-30  54.029999  371.570007  135.580002  54.049999  372.339996
2020-12-31  54.270000  371.230011  134.080002  54.450001  371.779999

               Volume
                 AAPL        KO        SPY
Date
2010-01-04  493729600  13870400  118944600
2010-01-05  601904800  23172400  111579900
2010-01-06  552160000  19264600  116074400
2010-01-07  477131200  13234600  131091100
2010-01-08  447610800  28712400  126402800
...               ...       ...        ...
2020-12-24   54930100   3265500   26457900
2020-12-28  124486200   9020500   39000400
2020-12-29  121047300   8320600   53680500
2020-12-30   96452100   8142700   49455300
2020-12-31   99116600   8495000   78520700

[2769 rows x 18 columns]

In [14]:
Stocks.to_csv('Stocks.csv')

In [28]:
stocks = pd.read_csv('Stocks.csv',header = [0,1],index_col=[0],parse_dates[0])

SyntaxError: positional argument follows keyword argument (673150881.py, line 1)

In [29]:
stocks

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.515212  19.081619   88.454185    7.643214  28.520000
2010-01-05    6.526476  18.850790   88.688332    7.656429  28.174999
2010-01-06    6.422665  18.844097   88.750771    7.534643  28.165001
2010-01-07    6.410791  18.797268   89.125435    7.520714  28.094999
2010-01-08    6.453413  18.449360   89.422005    7.570714  27.575001
...                ...        ...         ...         ...        ...
2020-12-24  130.404587  50.318054  358.332611  131.970001  53.439999
2020-12-28  135.068604  50.995991  361.410980  136.690002  54.160000
2020-12-29  133.270187  50.967743  360.721527  134.869995  54.130001
2020-12-30  132.133835  51.259632  361.236206  133.720001  54.439999
2020-12-31  131.116043  51.636265  363.071594  132.690002  54.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04  113.330002    7.660714  28.610001  113.389999    7.585000
2010-01-05  113.629997    7.699643  28.495001  113.680000    7.616071
2010-01-06  113.709999    7.686786  28.219999  113.989998    7.526786
2010-01-07  114.190002    7.571429  28.184999  114.330002    7.466071
2010-01-08  114.570000    7.571429  27.820000  114.620003    7.466429
...                ...         ...        ...         ...         ...
2020-12-24  369.000000  133.460007  53.549999  369.029999  131.100006
2020-12-28  372.170013  137.339996  54.439999  372.589996  133.509995
2020-12-29  371.459991  138.789993  54.490002  374.000000  134.339996
2020-12-30  371.989990  135.990005  54.630001  373.100006  133.399994
2020-12-31  373.880005  134.740005  54.930000  374.660004  131.720001

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2010-01-04  28.450001  111.510002    7.622500  28.580000  112.370003
2010-01-05  28.070000  112.849998    7.664286  28.424999  113.260002
2010-01-06  27.990000  113.430000    7.656429  28.174999  113.519997
2010-01-07  27.875000  113.180000    7.562500  28.165001  113.500000
2010-01-08  27.375000  113.660004    7.510714  27.730000  113.889999
...               ...         ...         ...        ...         ...
2020-12-24  53.020000  367.450012  131.320007  53.020000  368.079987
2020-12-28  53.730000  371.070007  133.990005  53.849998  371.739990
2020-12-29  54.020000  370.829987  138.050003  54.450001  373.809998
2020-12-30  54.029999  371.570007  135.580002  54.049999  372.339996
2020-12-31  54.270000  371.230011  134.080002  54.450001  371.779999

               Volume
                 AAPL        KO        SPY
Date
2010-01-04  493729600  13870400  118944600
2010-01-05  601904800  23172400  111579900
2010-01-06  552160000  19264600  116074400
2010-01-07  477131200  13234600  131091100
2010-01-08  447610800  28712400  126402800
...               ...       ...        ...
2020-12-24   54930100   3265500   26457900
2020-12-28  124486200   9020500   39000400
2020-12-29  121047300   8320600   53680500
2020-12-30   96452100   8142700   49455300
2020-12-31   99116600   8495000   78520700

[2769 rows x 18 columns]

In [30]:
stocks.columns

MultiIndex([('Adj Close', 'AAPL'),
            ('Adj Close',   'KO'),
            ('Adj Close',  'SPY'),
            (    'Close', 'AAPL'),
            (    'Close',   'KO'),
            (    'Close',  'SPY'),
            (     'High', 'AAPL'),
            (     'High',   'KO'),
            (     'High',  'SPY'),
            (      'Low', 'AAPL'),
            (      'Low',   'KO'),
            (      'Low',  'SPY'),
            (     'Open', 'AAPL'),
            (     'Open',   'KO'),
            (     'Open',  'SPY'),
            (   'Volume', 'AAPL'),
            (   'Volume',   'KO'),
            (   'Volume',  'SPY')],
           )

In [31]:
#convert to multi index to one tuple
stocks=stocks.columns